### ISSUE TITLE
Does this really require Python 3.8?

### ISSUE THREAD

**Issue by CVYY39** [ephes/wagtail_srcset#1]
This looks great and useful. Unfortunately not all hosted providers are updated to Python 3.8. The pyproject.toml here has a Python 3.8 requirement. 

In a quick review I didn't see any Python 3.8-specific code being used. Could this be bumped down to 3.7?

Thanks!

**Comment by ephes** [comment]
Good point. I just wanted to avoid to have to test against different python versions. But this shouldn't be a problem. Bumped it down to 3.6 since f-strings are used. Thanks for pointing this out :).
